/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienceSlugRouteImport } from './routes/experience.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceSlugRoute = ExperienceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExperienceRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/events': typeof EventsRouteWithChildren
  '/experience': typeof ExperienceRouteWithChildren
  '/tickets': typeof TicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/experience/$slug': typeof ExperienceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/events': typeof EventsRouteWithChildren
  '/experience': typeof ExperienceRouteWithChildren
  '/tickets': typeof TicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/experience/$slug': typeof ExperienceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/events': typeof EventsRouteWithChildren
  '/experience': typeof ExperienceRouteWithChildren
  '/tickets': typeof TicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/experience/$slug': typeof ExperienceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/events'
    | '/experience'
    | '/tickets'
    | '/events/$slug'
    | '/experience/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/events'
    | '/experience'
    | '/tickets'
    | '/events/$slug'
    | '/experience/$slug'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/events'
    | '/experience'
    | '/tickets'
    | '/events/$slug'
    | '/experience/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  EventsRoute: typeof EventsRouteWithChildren
  ExperienceRoute: typeof ExperienceRouteWithChildren
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$slug': {
      id: '/experience/$slug'
      path: '/$slug'
      fullPath: '/experience/$slug'
      preLoaderRoute: typeof ExperienceSlugRouteImport
      parentRoute: typeof ExperienceRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ExperienceRouteChildren {
  ExperienceSlugRoute: typeof ExperienceSlugRoute
}

const ExperienceRouteChildren: ExperienceRouteChildren = {
  ExperienceSlugRoute: ExperienceSlugRoute,
}

const ExperienceRouteWithChildren = ExperienceRoute._addFileChildren(
  ExperienceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  EventsRoute: EventsRouteWithChildren,
  ExperienceRoute: ExperienceRouteWithChildren,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
